export const GET_PARCEL = 'parcel/GET_PARCEL';
export const GET_PARCEL_SUCCESS = 'parcel/GET_PARCEL_SUCCESS';
export const GET_PARCEL_ERROR = 'parcel/GET_PARCEL_ERROR';

export const UPDATE_PARCEL = 'parcels/UPDATE_PARCEL';
export const UPDATE_PARCEL_SUCCESS = 'parcels/UPDATE_PARCEL_SUCCESS';
export const UPDATE_PARCEL_ERROR = 'parcels/UPDATE_PARCEL_ERROR';

export const UPDATE_PARCEL_STATUS = 'parcels/UPDATE_PARCEL_STATUS';

export const OPEN_PARCEL_STATUS = 'parcel/OPEN_PARCEL_STATUS';
export const CLOSE_PARCEL_STATUS = 'parcel/CLOSE_PARCEL_STATUS';

export const GET_PARCEL_STATUS_HISTORY = 'parcelStatusHistory/GET_PARCEL_STATUS_HISTORY';
export const GET_PARCEL_STATUS_HISTORY_SUCCESS = 'parcelStatusHistory/GET_PARCEL_STATUS_HISTORY_SUCCESS';
export const GET_PARCEL_STATUS_HISTORY_ERROR = 'parcelStatusHistory/GET_PARCEL_STATUS_HISTORY_ERROR';
