export const EDIT_PARCEL_OPEN = 'parcelEdit/EDIT_PARCEL_OPEN';
export const EDIT_PARCEL_SAVE_EDIT = 'parcelEdit/EDIT_PARCEL_SAVE_EDIT';
export const EDIT_PARCEL_SAVE_REQUEST = 'parcelEdit/EDIT_PARCEL_SAVE_REQUEST';
export const EDIT_PARCEL_DISCARD = 'parcelEdit/EDIT_PARCEL_DISCARD';
export const EDIT_PARCEL_CLOSE = 'parcelEdit/EDIT_PARCEL_CLOSE';

export const EDIT_PARCEL_SAVE_REQUEST_SUCCESS = 'parcelEdit/EDIT_PARCEL_SAVE_REQUEST_SUCCESS';
export const EDIT_PARCEL_SAVE_REQUEST_ERROR = 'parcelEdit/EDIT_PARCEL_SAVE_REQUEST_ERROR';
